[package]
name = "einstellung"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
console = "0.16.2"
shellexpand = "3.1.1"
similar = "2.7.0"
thiserror = "2.0.18"
